<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" file="PrivilegeDecorator_tests.py" name="PrivilegeDecorator_tests.PrivilegeDecorator_test-20191030171140" skipped="0" tests="1" time="0.001" timestamp="2019-10-30T17:11:40">
	<testcase classname="PrivilegeDecorator_tests.PrivilegeDecorator_test" file="src/unittest/python/PrivilegeDecorator_tests.py" line="13" name="test_user" time="0.001" timestamp="2019-10-30T17:11:40">
		<error message="name 'mockedUser' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/home/joseluis/Documentos/ITESO/DSO/decorator-practice/python/src/unittest/python/PrivilegeDecorator_tests.py", line 11, in setUp
    self.priv = PrivilegeDecorator(mockedUser)
NameError: name 'mockedUser' is not defined
]]>		</error>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
